DDP_INSPECTOR_PREFIX = 'lai:ddp-inspector';

DDP_INSPECTOR_SESSION_ACTIVE = DDP_INSPECTOR_PREFIX + '.active';
DDP_INSPECTOR_PANEL_ID = '.ddp-inspector-panel';

DDP_INSPECTOR_SUPPRESS_PING = DDP_INSPECTOR_PREFIX + '.suppressPing';
DDP_INSPECTOR_CONSOLE_ENABLED = DDP_INSPECTOR_PREFIX + '.console';
DDP_INSPECTOR_SEARCH_INPUT = DDP_INSPECTOR_PREFIX + '.search';
DDP_INSPECTOR_SEARCH_LIMIT = DDP_INSPECTOR_PREFIX + '.limit'

DDP_INSPECTOR_SEARCH_TEMPLATE = DDP_INSPECTOR_PREFIX + ':search';
DDP_INSPECTOR_SUBS_TEMPLATE = DDP_INSPECTOR_PREFIX + ':subscription';
DDP_INSPECTOR_METHODS_TEMPLATE = DDP_INSPECTOR_PREFIX + ':method';
DDP_INSPECTOR_COLLECTIONS_TEMPLATE = DDP_INSPECTOR_PREFIX + ':collection';
DDP_INSPECTOR_UNKNOWN_TEMPLATE = DDP_INSPECTOR_PREFIX + ':unknown';
